name: Publish documentation

# Publish documentation only on push to main.
on: 
  push:
    branches:
      - main

jobs:

  # Build and test project.
  publish-docs:
    strategy:
      matrix:
        build:
          - 1
        include:
          - build: 1
            build-type: Release
            python-version: '3.8'
    name: 'Ubuntu 20.04
      <type=${{ matrix.build-type }},
       python-version=${{ matrix.python-version }}>'
    runs-on: ubuntu-20.04
    steps:
      - name: Install CMake
        run: sudo apt-get install cmake
      - name: Install CMake
        run: sudo apt-get install doxygen
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Sphinx
        run: |
          python -m pip install --upgrade pip
          pip install sphinx
      - name: Install breathe
        run: |
          python -m pip install --upgrade pip
          pip install breathe
      - uses: actions/checkout@v2
      - name: Create build directories
        run: |
          mkdir _build
      - name: Configure
        run: |
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} \
                ..
        working-directory: _build
      - name: Build
        run: |
          cmake --build . \
                --verbose \
                --target all \
                --config ${{ matrix.build-type }}
        working-directory: _build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: _build/docs/sphinx/build
          CLEAN: true # Automatically remove deleted files from the deploy branch
